modules:
  - tasks/controllers.py
  - tasks/de_evaluators.py
  - tasks/de_initialisers.py
  - tasks/de_selectors.py
  - tasks/replacers.py
  - tasks/mutators.py
  - tasks/crossover.py
  - tasks/loggers.py
  - tasks/finalisers.py
runs: 2
pipelines:
  - name: DeJongOnePipeline
    controller:
      name: GenerationController
      params:
        - 1000
    initialisers:
      - name: DeJongOneInitialiser
        params:
          - [50, 20]
    tasks:
      - name: RandomSelector
      - name: DifferenceSelector
        params:
          - 2
      - name: CrossoverSelectorEach
      - name: DeMutator
        params:
          - 0.3
      - name: BinomialCrossover
        params:
          - 0.5
      - name: DeParentAllocatorCrossover
      - name: DeJongOneEvaluator
      - name: BetterReplacer
      - name: TerminalLogger
    finalisers:
      - name: DescriptionBuilder
      - name: ResultsBuilder
      - name: MongoDbSaver
        params:
          - ["ga_user", "ga_user", "ga", "results", "lifenoodles.com", "27018"]
