modules:
  - tasks/controllers.py
  - tasks/de_evaluators.py
  - tasks/de_initialisers.py
  - tasks/de_selectors.py
  - tasks/replacers.py
  - tasks/mutators.py
  - tasks/crossover.py
  - tasks/loggers.py
pipelines:
  - name: DeJongOnePipeline
    controller:
      name: GeneralController
      params:
        - 1000
    initialisers:
      - name: DeJongOneInitialiser
        params:
          - [100, 10]
    tasks:
      - name: RandomSelector
      - name: DifferenceSelector
        params:
          - 1
      - name: DeMutator
        params:
          - 0.5
      - name: BinomialCrossover
        params:
          - 0.5
      - name: DeJongOneEvaluator
      - name: BetterReplacer
      - name: TerminalLogger
    finalisers: []
