modules:
  - tasks/controllers.py
  - tasks/de_evaluators.py
  - tasks/de_initialisers.py
  - tasks/de_selectors.py
  - tasks/replacers.py
  - tasks/mutators.py
  - tasks/crossover.py
  - tasks/loggers.py
  - tasks/finalisers.py
runs: 1
pipelines:
  - name: RastriginSixPipeline_DE
    controller:
      name: GenerationController
      params:
        - 10000
    initialisers:
      - name: RastriginSixInitialiser
        params:
          - [50, 20]
    tasks:
      - name: RandomSelector
      - name: DifferenceSelectorAncestor
        params:
          - [1, 0.1]
      - name: DeMutator
        params:
          - 0.2
      - name: CrossoverSelectorEach
      - name: BinomialCrossover
        params:
          - 0.5
      - name: RastriginSixEvaluator
      - name: BetterReplacer
      - name: TerminalLogger
    finalisers:
      - name: DescriptionBuilder
      - name: ResultsBuilder
      - name: ResultsPrinter
