modules:
  - tasks/controllers.py
  - tasks/de_evaluators.py
  - tasks/de_initialisers.py
  - tasks/de_selectors.py
  - tasks/replacers.py
  - tasks/mutators.py
  - tasks/crossover.py
  - tasks/loggers.py
  - tasks/finalisers.py
  - tasks/constrainers.py
  - tasks/waiters.py
runs: 1
pipelines:
  - name: DeJongFourPipeline
    controller:
      name: GenerationController
      params:
        - 1000
    initialisers:
      - name: DeJongOneInitialiser
        params:
          - [10, 30]
    tasks:
      - name: RandomSelector
      - name: DifferenceSelectorAncestor
        params:
          - [1, 0.5]
      - name: CrossoverSelectorEach
      - name: DeMutator
        params:
          - 0.5
      - name: BinomialCrossover
        params:
          - 0.5
      - name: BoundsConstrainer
      - name: DeJongFourEvaluator
      - name: DeParentAllocatorCrossover
        params:
          - 0.1
      - name: BetterReplacer
      - name: TerminalLogger
    finalisers:
      - name: DescriptionBuilder
      - name: ResultsBuilder
      - name: ResultsPrinter
